// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewUser struct {
	Name  string  `json:"name"`
	Email *string `json:"email"`
}

type User struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Email *string `json:"email"`
}

type UsersQuery struct {
	// all users
	All []*User `json:"all"`
	// partner by id
	User *User `json:"user"`
}
